{% set name = "fgsl" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/reinh-bader/fgsl/archive/{{ version }}.tar.gz
  sha256: 8b6a02912b917e4544fed655b8e925c9b7160a063df57afcb35f064f351f1434

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - gnuconfig  # [unix]
    - make
    - autoconf
    - automake
    - m4
    - pkg-config
    - libtool
    - gettext
  host:
    - gsl ==2.7
    - libblas
    - libcblas

test:
  commands:
    - test -f $PREFIX/lib/libfgsl$SHLIB_EXT

about:
  home: https://doku.lrz.de/display/PUBLIC/FGSL+-+A+Fortran+interface+to+the+GNU+Scientific+Library
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Fortran interface to the GNU Scientific Library'
  description: |
    A portable, object-based Fortran interface to the GNU scientific
    library a collection of numerical routines for scientific computing.
  doc_url: https://doku.lrz.de/display/PUBLIC/FGSL+-+A+Fortran+interface+to+the+GNU+Scientific+Library
  dev_url: https://github.com/reinh-bader/fgsl 

extra:
  recipe-maintainers:
    - hhslepicka
